---
title: "Welch's t-test, Mann-Whitney U test, ANCOVA"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
        code_folding: hide
---

```{r}
rm(list=ls())
```

# Loading Packages

```{r}
# install.packages("data.table")
# install.packages("dplyr")
# install.packages("reshape2")
# install.packages("ggplot2")
# install.packages("ggrepel")
# install.packages("rstatix")
# install.packages("ggsignif")

suppressPackageStartupMessages({
    library(data.table)
    library(dplyr)
    library(reshape2)
    library(ggplot2)
    library(ggrepel)
    library(rstatix)
    library(ggsignif)
})
```

# Reading Data

## NPX table

```{r}
NPX_table <- fread(paste0(
    "..",
    "/..",
    "/00_Data",
    "/02_00_Exp_table.csv"))
```

# ANCOVA

## Control group, Experimental group, Test

```{r}
group_test_df <- data.frame()
for(tmp_test in c("Welch's t-test")){
    group_test_df <- rbind(
        group_test_df,
        data.frame(
            CG      = c("HC"),
            EG      = c("PD"),
            adj_var = NA,
            test    = tmp_test))
}

for(tmp_adj_var in c("age")){
    group_test_df <- rbind(
        group_test_df,
        data.frame(
            CG      = c("HC"),
            EG      = c("PD"),
            adj_var = tmp_adj_var,
            test    = "ANCOVA"))
}
```

## Variables to analyze

```{r}
group_var_df <- data.frame(
    group_var="Group",
    name_modified="Group")

cont_var_df <- data.frame(
    group_var=c("IL10", "IL17C", "NTF3", "uPA"),
    name_modified=c("IL10", "IL17C", "NTF3", "uPA"))
```

## Analysis result

```{r, fig.width=1.618*2, fig.height=2}
raw_data <- NPX_table |> data.frame()

result_table <- data.frame()
for(i in 1:nrow(group_test_df)){
    result_table2 <- data.frame()
    for(j in 1:nrow(cont_var_df)){
        if(is.na(group_test_df$adj_var[i]) |
           (group_test_df$adj_var[i]=="")){
            tmp_raw_data <-
                raw_data |>
                select_at(vars(c(
                    group_var_df$group_var,
                    cont_var_df$group_var[j])))
        }else{
            tmp_raw_data <-
                raw_data |>
                select_at(vars(c(
                    group_var_df$group_var,
                    cont_var_df$group_var[j],
                    group_test_df$adj_var[i] |>
                        strsplit(";",fixed=TRUE) |>
                        unlist())))
        }
        
        tmp_raw_data <- tmp_raw_data |>
            mutate(Group = ifelse(
                .data[[group_var_df$group_var]] %in%
                    (group_test_df$CG[i] |>
                         strsplit(";",fixed=TRUE) |>
                         unlist()),
                0, ifelse(.data[[group_var_df$group_var]] %in%
                              (group_test_df$EG[i] |>
                                   strsplit(";",fixed=TRUE) |>
                                   unlist()),
                          1, NA))) |>
            na.omit()
        
        if(group_test_df$test[i] == "Welch's t-test"){
            tmp_result <- 
                as.formula(paste0(
                    cont_var_df$group_var[j],
                    " ~ Group")) |>
                t.test(data=tmp_raw_data)
            tmp_p_value <- tmp_result$p.value
            tmp_diff <-
                mean(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==1])-
                mean(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==0])
        }
        if(group_test_df$test[i] == "Mann-Whitney U test"){
            tmp_result <- 
                as.formula(paste0(
                    cont_var_df$group_var[j],
                    " ~ Group")) |>
                wilcox.test(data=tmp_raw_data,exact =TRUE)
            tmp_p_value <- tmp_result$p.value
            tmp_diff <-
                median(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==1])-
                median(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==0])
        }
        if(group_test_df$test[i] == "ANCOVA"){
            tmp_result <- 
                as.formula(paste0(
                    cont_var_df$group_var[j],
                    " ~ Group + ",
                    group_test_df$adj_var[i] |>
                        strsplit(";",fixed=TRUE) |>
                        unlist() |>
                        paste0(collapse="+"))) |>
                aov(data=tmp_raw_data) |>
                Anova(type="III")
            tmp_p_value <- tmp_result["Group", "Pr(>F)"]
            
            tmp_lm <- as.formula(paste0(
                cont_var_df$group_var[j],
                " ~ Group + ",
                group_test_df$adj_var[i] |>
                    strsplit(";",fixed=TRUE) |>
                    unlist() |>
                    paste0(collapse="+"))) |>
                lm(data=tmp_raw_data) |>
                coef()
            tmp_diff <- tmp_lm["Group"]
        }
        result_table2 <- rbind(
            result_table2,
            data.frame(
                CG          = group_test_df$CG[i],
                EG          = group_test_df$EG[i],
                adj_var     = group_test_df$adj_var[i],
                Test        = group_test_df$test[i],
                var         = cont_var_df$group_var[j],
                var_name    = cont_var_df$name_modified[j],
                EG_minus_CG = tmp_diff,
                p_value     = tmp_p_value))
    }
    result_table2 <- result_table2 |>
        mutate(adj_p=p.adjust(p_value, method="fdr"))
    result_table <- rbind(result_table, result_table2)
}
```

```{r}
result_table |>
    fwrite("./test_result.csv")
```

# Plot

## IL17C

```{r, fig.width=2*1, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "IL17C")) |>
    na.omit()

minval <- min(anal_data$IL17C)
maxval <- max(anal_data$IL17C)

anal_data |>
    ggplot() +
    aes(
        x       =Group,
        y       =IL17C,
        group_by=Group,
        colour  =Group) +
    geom_boxplot(
        outliers=FALSE) +
    stat_boxplot(
        geom    ='errorbar',
        width   =0.2) +
    geom_jitter(
        position=position_jitterdodge(jitter.width = 0.4)) +
    ylab(expression(log[2](IL17C~(pg/ml)))) +
    theme_classic() +
    theme(
        legend.position="none",
        axis.title.x   =element_blank(),
        panel.grid     =element_blank()) +
    geom_signif(
        comparisons =list(c("HC", "PD")),
        aes(y=0.1*(maxval-minval) + maxval),
        annotation  ="**",
        tip_length  =0,
        colour      ="black",
        vjust       =0) +
    ylim(c(NA, 0.2*(maxval-minval) + maxval)) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

```{r, fig.width=2*1.618, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "IL17C", "age")) |>
    na.omit()

lm_result <- lm(
    formula=IL17C~age+Group,
    anal_data)

x_min <- min(anal_data$age)
x_max <- max(anal_data$age)

anal_data |>
    ggplot() +
    aes(
        x       =age,
        y       =IL17C,
        colour  =Group) +
    geom_point() +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"],
        slope    =lm_result$coefficients["age"],
        colour   ="#F8766D",
        linewidth=1) +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"] +
            lm_result$coefficients["GroupPD"],
        slope    =lm_result$coefficients["age"],
        colour   ="#619CFF",
        linewidth=1) +
    ylab(expression(log[2](IL17C~(pg/ml)))) +
    xlab("Age") +
    theme_classic() +
    theme(
        legend.title=element_blank(),
        panel.grid  =element_blank()) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

## IL10

```{r, fig.width=2*1, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "IL10")) |>
    na.omit()

minval <- min(anal_data$IL10)
maxval <- max(anal_data$IL10)

anal_data |>
    ggplot() +
    aes(
        x       =Group,
        y       =IL10,
        group_by=Group,
        colour  =Group) +
    geom_boxplot(
        outliers=FALSE) +
    stat_boxplot(
        geom    ='errorbar',
        width   =0.2) +
    geom_jitter(
        position=position_jitterdodge(jitter.width = 0.4)) +
    ylab(expression(log[2](IL10~(pg/ml)))) +
    theme_classic() +
    theme(
        legend.position="none",
        axis.title.x   =element_blank(),
        panel.grid     =element_blank()) +
    geom_signif(
        comparisons =list(c("HC", "PD")),
        aes(y=0.1*(maxval-minval) + maxval),
        annotation  ="*",
        tip_length  =0,
        colour      ="black",
        vjust       =0) +
    ylim(c(NA, 0.2*(maxval-minval) + maxval)) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

```{r, fig.width=2*1.618, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "IL10", "age")) |>
    na.omit()

lm_result <- lm(
    formula=IL10~age+Group,
    anal_data)

x_min <- min(anal_data$age)
x_max <- max(anal_data$age)

anal_data |>
    ggplot() +
    aes(
        x       =age,
        y       =IL10,
        colour  =Group) +
    geom_point() +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"],
        slope    =lm_result$coefficients["age"],
        colour   ="#F8766D",
        linewidth=1) +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"] +
            lm_result$coefficients["GroupPD"],
        slope    =lm_result$coefficients["age"],
        colour   ="#619CFF",
        linewidth=1) +
    ylab(expression(log[2](IL10~(pg/ml)))) +
    xlab("Age") +
    theme_classic() +
    theme(
        legend.title=element_blank(),
        panel.grid  =element_blank()) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

## NTF3

```{r, fig.width=2*1, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "NTF3")) |>
    na.omit()

minval <- min(anal_data$NTF3)
maxval <- max(anal_data$NTF3)

anal_data |>
    ggplot() +
    aes(
        x       =Group,
        y       =NTF3,
        group_by=Group,
        colour  =Group) +
    geom_boxplot(
        outliers=FALSE) +
    stat_boxplot(
        geom    ='errorbar',
        width   =0.2) +
    geom_jitter(
        position=position_jitterdodge(jitter.width = 0.4)) +
    ylab(expression(log[2](NTF3~(pg/ml)))) +
    theme_classic() +
    theme(
        legend.position="none",
        axis.title.x   =element_blank(),
        panel.grid     =element_blank()) +
    geom_signif(
        comparisons =list(c("HC", "PD")),
        aes(y=0.1*(maxval-minval) + maxval),
        annotation  ="*",
        tip_length  =0,
        colour      ="black",
        vjust       =0) +
    ylim(c(NA, 0.2*(maxval-minval) + maxval)) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

```{r, fig.width=2*1.618, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "NTF3", "age")) |>
    na.omit()

lm_result <- lm(
    formula=NTF3~age+Group,
    anal_data)

x_min <- min(anal_data$age)
x_max <- max(anal_data$age)

anal_data |>
    ggplot() +
    aes(
        x       =age,
        y       =NTF3,
        colour  =Group) +
    geom_point() +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"],
        slope    =lm_result$coefficients["age"],
        colour   ="#F8766D",
        linewidth=1) +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"] +
            lm_result$coefficients["GroupPD"],
        slope    =lm_result$coefficients["age"],
        colour   ="#619CFF",
        linewidth=1) +
    ylab(expression(log[2](NTF3~(pg/ml)))) +
    xlab("Age") +
    theme_classic() +
    theme(
        legend.title=element_blank(),
        panel.grid  =element_blank()) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

## uPA

```{r, fig.width=2*1, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "uPA")) |>
    na.omit()

minval <- min(anal_data$uPA)
maxval <- max(anal_data$uPA)

anal_data |>
    ggplot() +
    aes(
        x       =Group,
        y       =uPA,
        group_by=Group,
        colour  =Group) +
    geom_boxplot(
        outliers=FALSE) +
    stat_boxplot(
        geom    ='errorbar',
        width   =0.2) +
    geom_jitter(
        position=position_jitterdodge(jitter.width = 0.4)) +
    ylab(expression(log[2](uPA~(pg/ml)))) +
    theme_classic() +
    theme(
        legend.position="none",
        axis.title.x   =element_blank(),
        panel.grid     =element_blank()) +
    geom_signif(
        comparisons =list(c("HC", "PD")),
        aes(y=0.1*(maxval-minval) + maxval),
        annotation  ="**",
        tip_length  =0,
        colour      ="black",
        vjust       =0) +
    ylim(c(NA, 0.2*(maxval-minval) + maxval)) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

```{r, fig.width=2*1.618, fig.height=2*1}
anal_data <-
    NPX_table |>
    select_at(c("Group", "uPA", "age")) |>
    na.omit()

lm_result <- lm(
    formula=uPA~age+Group,
    anal_data)

x_min <- min(anal_data$age)
x_max <- max(anal_data$age)

anal_data |>
    ggplot() +
    aes(
        x       =age,
        y       =uPA,
        colour  =Group) +
    geom_point() +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"],
        slope    =lm_result$coefficients["age"],
        colour   ="#F8766D",
        linewidth=1) +
    geom_abline(
        intercept=lm_result$coefficients["(Intercept)"] +
            lm_result$coefficients["GroupPD"],
        slope    =lm_result$coefficients["age"],
        colour   ="#619CFF",
        linewidth=1) +
    ylab(expression(log[2](uPA~(pg/ml)))) +
    xlab("Age") +
    theme_classic() +
    theme(
        legend.title=element_blank(),
        panel.grid  =element_blank()) +
    scale_colour_manual(values=c("#F8766D", "#619CFF"))
```

# sessionInfo()

```{r}
date()
```

```{r}
sessionInfo()
```
