---
title: "Welch's t-test, Mann-Whitney U test, ANCOVA"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
        code_folding: hide
---

```{r}
rm(list=ls())
```

# Loading Packages

```{r}
# install.packages("data.table")
# install.packages("dplyr")
# install.packages("reshape2")
# install.packages("ggplot2")
# install.packages("ggrepel")
# install.packages("rstatix")

suppressPackageStartupMessages({
    library(data.table)
    library(dplyr)
    library(reshape2)
    library(ggplot2)
    library(ggrepel)
    library(rstatix)
})
```

# Reading Data

## NPX table

```{r}
NPX_table <- fread(paste0(
    "..",
    "/..",
    "/00_Data",
    "/01_00_NPX_table.csv"))
```

## Prot num table

```{r}
prot_num_table <- fread(paste0(
    "..",
    "/..",
    "/00_Data",
    "/01_01_Prot_num_table.csv"))
```

# ANCOVA

## Control group, Experimental group, Test

```{r}
group_test_df <- data.frame()
for(tmp_test in c("Mann-Whitney U test")){
    group_test_df <- rbind(
        group_test_df,
        data.frame(
            CG      = c("HC"),
            EG      = c("PD"),
            adj_var = NA,
            test    = tmp_test))
}
```

## Variables to analyze

```{r}
group_var_df <- data.frame(
    group_var="Sample.Group",
    name_modified="Group")

cont_var_df <- data.frame(
    group_var=prot_num_table$Prot_num,
    name_modified=prot_num_table$Prot_name)
```

## Analysis result

```{r, fig.width=1.618*2, fig.height=2}
raw_data <- NPX_table |> data.frame()

result_table <- data.frame()
for(i in 1:nrow(group_test_df)){
    result_table2 <- data.frame()
    for(j in 1:nrow(cont_var_df)){
        if(is.na(group_test_df$adj_var[i]) |
           (group_test_df$adj_var[i]=="")){
            tmp_raw_data <-
                raw_data |>
                select_at(vars(c(
                    group_var_df$group_var,
                    cont_var_df$group_var[j])))
        }else{
            tmp_raw_data <-
                raw_data |>
                select_at(vars(c(
                    group_var_df$group_var,
                    cont_var_df$group_var[j],
                    group_test_df$adj_var[i] |>
                        strsplit(";",fixed=TRUE) |>
                        unlist())))
        }
        
        tmp_raw_data <- tmp_raw_data |>
            mutate(Group = ifelse(
                .data[[group_var_df$group_var]] %in%
                    (group_test_df$CG[i] |>
                         strsplit(";",fixed=TRUE) |>
                         unlist()),
                0, ifelse(.data[[group_var_df$group_var]] %in%
                              (group_test_df$EG[i] |>
                                   strsplit(";",fixed=TRUE) |>
                                   unlist()),
                          1, NA))) |>
            na.omit()
        
        if(group_test_df$test[i] == "Welch's t-test"){
            tmp_result <- 
                as.formula(paste0(
                    cont_var_df$group_var[j],
                    " ~ Group")) |>
                t.test(data=tmp_raw_data)
            tmp_p_value <- tmp_result$p.value
            tmp_diff <-
                mean(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==1])-
                mean(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==0])
        }
        if(group_test_df$test[i] == "Mann-Whitney U test"){
            tmp_result <- 
                as.formula(paste0(
                    cont_var_df$group_var[j],
                    " ~ Group")) |>
                wilcox.test(data=tmp_raw_data,exact =TRUE)
            tmp_p_value <- tmp_result$p.value
            tmp_diff <-
                median(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==1])-
                median(
                    tmp_raw_data[[
                        cont_var_df$group_var[j]]][
                            tmp_raw_data$Group==0])
        }
        if(group_test_df$test[i] == "ANCOVA"){
            tmp_result <- 
                as.formula(paste0(
                    cont_var_df$group_var[j],
                    " ~ Group + ",
                    group_test_df$adj_var[i] |>
                        strsplit(";",fixed=TRUE) |>
                        unlist() |>
                        paste0(collapse="+"))) |>
                aov(data=tmp_raw_data) |>
                Anova(type="III")
            tmp_p_value <- tmp_result["Group", "Pr(>F)"]
            
            tmp_lm <- as.formula(paste0(
                cont_var_df$group_var[j],
                " ~ Group + ",
                group_test_df$adj_var[i] |>
                    strsplit(";",fixed=TRUE) |>
                    unlist() |>
                    paste0(collapse="+"))) |>
                lm(data=tmp_raw_data) |>
                coef()
            tmp_diff <- tmp_lm["Group"]
        }
        result_table2 <- rbind(
            result_table2,
            data.frame(
                CG          = group_test_df$CG[i],
                EG          = group_test_df$EG[i],
                adj_var     = group_test_df$adj_var[i],
                Test        = group_test_df$test[i],
                var         = cont_var_df$group_var[j],
                var_name    = cont_var_df$name_modified[j],
                EG_minus_CG = tmp_diff,
                p_value     = tmp_p_value))
    }
    result_table2 <- result_table2 |>
        mutate(adj_p=p.adjust(p_value, method="fdr"))
    result_table <- rbind(result_table, result_table2)
}
```

```{r}
result_table |>
    fwrite("./test_result.csv")
```

# Volcano plot

```{r, fig.width=1.618*2, fig.height=2, warning=FALSE}
symmetric_limits <- function(x) {
    max <- max(abs(x))
    c(-max, max)}

cut_diff <- 0
cut_pval <- 0.05
cut_label_pval <- 0.05

for(i in 1:nrow(group_test_df)){
    cat("##############################\n")
    cat(group_test_df$CG[i], " vs ",
        group_test_df$EG[i], " | ",
        group_test_df$adj_var[i], "\n")
    cat("Test =", group_test_df$test[i] ,"\n")
    if(is.na(group_test_df$adj_var[i])){
        tmp_result_table <- result_table |>
            filter(CG == group_test_df$CG[i]) |>
            filter(EG == group_test_df$EG[i]) |>
            filter(is.na(adj_var)) |>
            filter(Test == group_test_df$test[i])
    }else{
        tmp_result_table <- result_table |>
            filter(CG == group_test_df$CG[i]) |>
            filter(EG == group_test_df$EG[i]) |>
            filter(adj_var == group_test_df$adj_var[i]) |>
            filter(Test == group_test_df$test[i])
    }
    
    tmp_result_table <- tmp_result_table |>
        mutate(
            class = ifelse(
                (EG_minus_CG < -cut_diff) &
                    (p_value < cut_pval),
                "Down",
                ifelse((EG_minus_CG > cut_diff) &
                           (p_value < cut_pval),
                       "Up", "NS")),
            text = ifelse(
                (abs(EG_minus_CG) > cut_diff) &
                    (p_value < cut_label_pval),
                var_name,
                ""),
            minus_log10_p_value = -log10(p_value))
    
    print(
        tmp_result_table |>
            mutate(
                class = ifelse(
                    (EG_minus_CG < -cut_diff) &
                        (p_value < cut_pval),
                    "Down",
                    ifelse((EG_minus_CG > cut_diff) &
                               (p_value < cut_pval),
                           "Up", "NS")),
                text = ifelse(
                    (abs(EG_minus_CG) > cut_diff) &
                        (p_value < cut_label_pval),
                    var_name,
                    ""),
                minus_log10_p_value = -log10(p_value)) |>
            ggplot() +
            aes(x=EG_minus_CG, y=minus_log10_p_value) +
            geom_point(aes(colour=class)) +
            geom_hline(
                yintercept = -log10(cut_pval),
                linetype = "dashed") +
            geom_vline(
                xintercept = c(-cut_diff, cut_diff),
                linetype = "dashed") + 
            geom_text_repel(
                aes(label = text),
                size=2.5,
                max.time=1,
                max.overlaps=15) +
            scale_x_continuous(limits = symmetric_limits) + 
            scale_y_continuous(limits = c(0,NA)) + 
            scale_colour_manual(
                values = c("#E0E0E0","#F8766D","#619CFF"),
                limits = c("NS", "Up", "Down")) +
            theme_bw() +
            xlab(expression(PD(NPX)-HC(NPX))) +
            ylab(expression(-log[10]~(p-value))) + 
            theme(legend.position="none")
    )
}
```

# sessionInfo()

```{r}
date()
```

```{r}
sessionInfo()
```
